#!/bin/bash
set -e

PID=$$
KAFKA_RESULT="/tmp/btcpool-test-jobmaker.$PID.log"
KAFKA_CONSUMER="docker exec btc_kafka_1 /opt/kafka/bin/kafka-console-consumer.sh --bootstrap-server kafka:9092"
KAFKA_PRODUCER="docker exec -i btc_kafka_1 /opt/kafka/bin/kafka-console-producer.sh --broker-list kafka:9092"
WAIT_FOR_IT="$BASE_DIR/../../deploy/wait-for-it.sh"
DOCKER_COMPOSE="docker-compose --no-ansi"

cd "$BASE_DIR"

echo "clear old docker compose..."
$DOCKER_COMPOSE down >>$STDOUT

echo "start jobmaker (5s)..."
$DOCKER_COMPOSE up jobmaker >>$STDOUT &
sleep 5

outputTestData() {
    cat "$BASE_DIR/testdata/rawgbts-1.log" \
        "$BASE_DIR/testdata/rawgbts-2.log" \
        "$BASE_DIR/testdata/rawgbts-3.log" \
    | while read line; do
        line=${line/@TIME@/$(date +%s)}
        echo $line
        sleep 1
    done
}

{
    echo "send RawGbts in the background..."
    outputTestData | $KAFKA_PRODUCER --topic RawGbt
} &

echo "consome StratumJob from kafka (60s)..."
$KAFKA_CONSUMER --topic StratumJob --from-beginning >$KAFKA_RESULT &
KAFKA_CONSUMER_PID=$!
sleep 60
kill $KAFKA_CONSUMER_PID

line=`cat $KAFKA_RESULT | wc -l`
if [ $line -lt 20 ]; then
    echo "There should be 20 StratumJobs but only $line"
    exit 1
else
    echo "Got $line StratumJobs from Kafka, OK."
fi

echo "Checking StratumJobs..."
php "$BASE_DIR/helper/check-stratumjob.php" "$KAFKA_RESULT"

#rm $KAFKA_RESULT
$DOCKER_COMPOSE down >>$STDOUT
