#! /bin/bash
#
# run shell for litecoind
#
# @copyright btc.com
# @author zhibiao.pan@bitmain.com
#
export LC_ALL=C
SROOT=$(cd $(dirname "$0"); pwd)
cd $SROOT

OPT_ZMQ="-zmqpubrawblock=tcp://0.0.0.0:9331 -zmqpubrawtx=tcp://0.0.0.0:9331 -zmqpubhashtx=tcp://0.0.0.0:9331 -zmqpubhashblock=tcp://0.0.0.0:9331"
litecoind -conf="/root/.litecoin/litecoin.conf" -datadir="/root/.litecoin" $OPT_ZMQ
