#! /bin/bash
#
# run shell for bitcoind: testnet3
#
# @copyright btc.com
# @author zhibiao.pan@bitmain.com
#
export LC_ALL=C
SROOT=$(cd $(dirname "$0"); pwd)
cd $SROOT

# copy default log file
if ! [ -e "/root/.bitcoin/log.conf" ]; then
    cp /root/default-conf/log.conf /root/.bitcoin/log.conf
fi
if ! [ -e "/root/.bitcoin/sbtc.conf" ]; then
    ln -s ./bitcoin.conf /root/.bitcoin/sbtc.conf
fi

OPT_PORT="-port=18333 -rpcport=18332"
OPT_ZMQ="-zmqpubrawblock=tcp://0.0.0.0:18331 -zmqpubrawtx=tcp://0.0.0.0:18331 -zmqpubhashtx=tcp://0.0.0.0:18331 -zmqpubhashblock=tcp://0.0.0.0:18331"
bitcoind -testnet -conf="/root/.bitcoin/bitcoin.conf" -datadir="/root/.bitcoin" $OPT_PORT $OPT_ZMQ
