#! /bin/bash
#
# run shell for bitcoind
#
export LC_ALL=C
SROOT=$(cd $(dirname "$0"); pwd)
cd $SROOT

OPT_ZMQ="-zmqpubhashtx=tcp://0.0.0.0:8331 -zmqpubhashblock=tcp://0.0.0.0:8331"
bitcoind -datadir="/work/bitcoin1" $OPT_ZMQ
